backend:
  name: git-gateway
  branch: master

logo_url: https://heuristic-brattain-948037.netlify.app/icon.png

media_folder: static/images
public_folder: /images

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About'
        name: 'about'
        extension: 'json'
        file: 'content/about.json'
        create: true
        editor:
          preview: true
        widget: 'list'
        fields:
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: Skills
            name: skills
            widget: list
            field: { label: Skills, name: skills, widget: string }
          - label: Education
            name: education
            widget: list
            fields:
              [
                { label: Date, name: date, widget: string },
                { label: Info, name: info, widget: string },
                { label: Entity, name: entity, widget: string },
                { label: Description, name: description, widget: string }
              ]
          - label: Experience
            name: experience
            widget: list
            fields:
              [
                { label: Date, name: date, widget: string },
                { label: Info, name: info, widget: string },
                { label: Entity, name: entity, widget: string },
                { label: Description, name: description, widget: string }
              ]
      - label: 'Portfolio'
        name: 'portfolio'
        extension: 'json'
        file: 'content/portfolio_test.json'
        create: true
        editor:
          preview: true
        widget: 'list'
        fields:
          - label: Proyects
            name: proyects
            widget: list
            fields:
              [
                { label: Name, name: name, widget: string },
                { label: Thumbnail, name: thumbnail, widget: image },
                { label: Image, name: image, widget: image },
                { label: Description, name: description, widget: string },
                { label: Repositorie, name: repositorie, widget: string },
                { label: Tech, name: tech, widget: string },
                { label: Url, name: url, widget: string }
              ]
