backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images
collections:
  - name: 'about'
    label: 'About'
    extension: 'json'
    folder: 'content/about_test'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Skills', name: 'title', widget: 'string' }
