backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About'
        name: 'about'
        extension: 'json'
        file: 'content/about_test.json'
        create: true
        editor:
          preview: true
        widget: 'list'
        fields:
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Skills', name: 'skills', widget: 'string' }
          - label: Education
            name: education
            widget: list
            fields:
              [
                { name: Date, label: date, widget: string },
                { name: Info, label: info, widget: string },
                { name: Entity, label: entity, widget: string },
                { name: Description, label: description, widget: string }
              ]
          - label: Experience
            name: experience
            widget: list
            fields:
              [
                { name: Date, label: date, widget: string },
                { name: Info, label: info, widget: string },
                { name: Entity, label: entity, widget: string },
                { name: Description, label: description, widget: string }
              ]
